[package]
name = "brewdrivers"
version = "0.4.2"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"
description = "Brewkit drivers"
documentation = "https://docs.rs/brewdrivers/"
homepage = "https://docs.rs/crate/brewdrivers/"
repository = "https://github.com/NavasotaBrewing/brewdrivers"
readme = "readme.md"
keywords = ["serial", "hardware", "brewing", "control", "driver"]
categories = ["hardware-support", "network-programming"]
license = "MIT"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-none-linux-gnueabihf-gcc"

# [target.armv7-unknown-linux-gnueabihf]
# image = "navasotabrewing/rtu-compiler:0.1.1"


[dependencies]
hex = "0.3.2"
serialport = "3.3.0"
retry = "0.5.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rocket = "0.4.2"
rocket_cors = "0.5.0"
reqwest = "0.9.20"
futures = "0.1"
tokio-modbus = { version = "0.3.5", default-features = false, features = ["rtu"] }
tokio-core = "*"
tokio-serial = "3.3.0"
shrust = "0.0.7"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]
