[package]
name = "brewdrivers"
version = "0.6.0"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"
description = "Brewkit drivers"
documentation = "https://docs.rs/brewdrivers/"
homepage = "https://docs.rs/crate/brewdrivers/"
repository = "https://github.com/NavasotaBrewing/brewdrivers"
readme = "readme.md"
keywords = ["serial", "hardware", "brewing", "control", "driver"]
categories = ["hardware-support", "network-programming"]
license = "MIT"

[dependencies]
hex = "0.3.2"
# This is for the STR1
serialport = "4.0"
futures = "0.3"
tokio-modbus = { version = "0.4", default-features = false, features = ["rtu"] }
tokio = { version = "0.2", features = ["full"] }
tokio-serial = "4.0"
# shrust = "0.0.7"


[dependencies.serde]
version = "1.0"
optional = true

[dev-dependencies]
serial_test = "0.4.0"

[features]
default = []
# This enables NavasotaBrewing/network to use parts of brewdrivers
# in its network communications. You shouldn't need to enable it if
# you're just using the CLI or drivers as a library
network = ["serde"]
