[package]
name = "brewdrivers"
version = "0.2.1"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"
description = "Brewkit drivers"
documentation = "https://github.com/NavasotaBrewing/brewdrivers"
homepage = "https://github.com/NavasotaBrewing/brewdrivers"
repository = "https://github.com/NavasotaBrewing/brewdrivers"
readme = "readme.md"
keywords = ["serial", "hardware", "brewing", "control", "driver"]
categories = ["hardware-support", "network-programming"]
license = "MIT"

# [[bin]]
# path = "./src"
# name = "main"
# doc = false

[dependencies]
hex = "0.3.2"
serialport = "3.3.0"
clap = "2.33.0"

