[package]
name = "brewdrivers"
version = "0.3.0"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"
description = "Brewkit drivers"
documentation = "https://docs.rs/brewdrivers/"
homepage = "https://docs.rs/crate/brewdrivers/"
repository = "https://github.com/NavasotaBrewing/brewdrivers"
readme = "readme.md"
keywords = ["serial", "hardware", "brewing", "control", "driver"]
categories = ["hardware-support", "network-programming"]
license = "MIT"

[dependencies]
hex = "0.3.2"
serialport = "3.3.0"
clap = "2.33.0"
retry = "0.5.1"
# tokio-modbus = "*"
# futures = "0.1.28"
# tokio = "*"
