[package]
name = "brewdrivers"
version = "0.6.0"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"
description = "Brewkit drivers"
documentation = "https://docs.rs/brewdrivers/"
homepage = "https://docs.rs/crate/brewdrivers/"
repository = "https://github.com/NavasotaBrewing/brewdrivers"
readme = "readme.md"
keywords = ["serial", "hardware", "brewing", "control", "driver"]
categories = ["hardware-support", "network-programming"]
license = "MIT"

[dependencies]
hex = "0.3.2"
serialport = "4.0"
retry = "0.5.1"
futures = "0.1"
tokio-modbus = { version = "0.3.5", default-features = false, features = ["rtu"] }
# Deprecation notice: tokio-core has been deprecated.
# See more here: https://github.com/tokio-rs/tokio-core
tokio-core = "0.1"
tokio-serial = "3.3.0"
shrust = "0.0.7"



[dependencies.serde]
version = "1.0"
optional = true

[features]
default = []
# This enables NavasotaBrewing/network to use parts of brewdrivers
# in its network communications. You shouldn't need to enable it if
# you're just using the CLI or drivers as a library
network = ["serde"]