[build.env]
passthrough = [
    # "PKG_CONFIG_PATH",
    "RUST_BACKTRACE"
]

[target.armv7-unknown-linux-gnueabihf]
image = "navasotabrewing/rtu-compiler:0.2.1"
# linker = "arm-none-linux-gnueabihf-gcc"
linker = "arm-linux-gnueabihf-gcc"